// Generated by CoffeeScript 1.12.6
module.exports = {
  cloneOptions: function(obj, newProps) {
    var a, k;
    a = {};
    for (k in obj) {
      a[k] = newProps[k] || obj[k];
    }
    return a;
  }
};
