#!/usr/bin/env python
# Requires output json file to be specified

from attitude import Orientation
from attitude.test import load_test_plane
from attitude.error.axes import sampling_axes, angular_errors
import numpy as N
from sys import argv
from json import dump

def serialize(pca, **kwargs):
    """
    Serialize an orientation object to a dict suitable
    for JSON
    """
    strike, dip, rake = pca.strike_dip_rake()
    hyp_axes = sampling_axes(pca)

    return dict(
        **kwargs,
        principal_axes = pca.axes.tolist(),
        hyperbolic_axes = hyp_axes.tolist(),
        n_samples = pca.n,
        strike=strike, dip=dip, rake=rake,
        angular_errors=[2*N.degrees(i)
            for i in angular_errors(hyp_axes)])

planes = []
for name in ['poorly_defined', 'well_defined']:
    array = load_test_plane(name)
    pca = Orientation(array)
    res = pca.to_mapping()
    res["name"] = name
    planes.append(res)

with open(argv[1], 'w') as f:
    dump(planes, f, indent=4)

