#!/usr/bin/env zsh

# Create a virtualenv to work in
python -m venv .venv && .venv/bin/activate
# Install requirements
pip install --requirement requirements.pip

python scripts/generate-json.py _static/planes.json

make html

ls
