#!/bin/bash

root=$(git rev-parse --show-toplevel)
docs=$root/docs
build=$docs/_build/html
hash=$(git rev-parse --short HEAD)
branch=$(git rev-parse --abbrev-ref HEAD)
# build the docs
cd $docs
make clean
make html

# Move to subdirectory and publish
cd $build
git status
git add -A
git commit -m "Publishing docs for $hash on $branch"
git push origin gh-pages

