#!/bin/bash

# build the docs
cd docs
make clean
make html
cd ..

# git diff-index --quiet HEAD --
# commit and push
git add -A
git commit -m "building and pushing docs"
git push github master

# switch branches and pull the data we want
git checkout gh-pages
rm -rf .
touch .nojekyll
git checkout master docs/_build/html
mv ./docs/build/html/* ./
rm -rf ./docs
git add -A
git commit -m "Publishing docs corresponding to master:$(git rev-parse --short master)"
git push origin gh-pages

# switch back
git checkout master
