#!/usr/bin/env zsh
# Script to build documentation and serve on
# localhost:8000

style_dir=theme/static

mkdir -p $style_dir

#stylus -w -o $style_dir theme/main.styl & \
SPHINXBUILD=sphinx-autobuild make html
