#!/usr/bin/env zsh
# Script to build documentation and serve on
# localhost:8000

build_dir=_build/html
style_dir=$build_dir/_static

mkdir -p $style_dir

stylus -w -o $style_dir main.styl & \
  SPHINXBUILD=sphinx-autobuild make html
