#!/bin/bash
export BASE='ui-test'
export DATA='ui-test/data'
python $BASE/process-onis-planes.py $BASE/test-site/data.json
find src -name '*.*' | \
  entr ./build --rollup-only & \
  $(npm bin)/webpack --config webpack.ui.js --watch

