#!/bin/bash
export BASE='ui-test'
export DATA='ui-test/data'
python $BASE/process-onis-planes.py graphical-tests/ui/data.json

function finish {
  if [[ -n $pid ]]; then
    kill $pid
  fi
}

$(npm bin)/browser-sync start --server & \
find src | entr ./build --rollup-only
  #$(npm bin)/webpack --config webpack.ui.js --watch

trap finish EXIT


